// The 7 chakras — core data used across the app.
// Sanskrit names + Devanagari glyphs (like 9Lives uses Chinese characters for elements).
// Planet correspondences follow Western esoteric tradition.

export const CHAKRAS = [
  {
    id: 'root',
    number: 1,
    name: 'Root',
    sanskrit: 'Muladhara',
    devanagari: 'मूलाधार',
    element: 'earth',
    planet: 'Saturn',
    zodiac: ['Capricorn', 'Taurus', 'Virgo'],
    location: 'Base of the spine',
    theme: 'Ground, survival, belonging',
    color: 'var(--chakra-root)',
    hex: '#c26848',
    ageRange: { start: 0, end: 7 },
  },
  {
    id: 'sacral',
    number: 2,
    name: 'Sacral',
    sanskrit: 'Svadhisthana',
    devanagari: 'स्वाधिष्ठान',
    element: 'water',
    planet: 'Moon',
    zodiac: ['Cancer', 'Scorpio', 'Pisces'],
    location: 'Lower abdomen',
    theme: 'Feeling, flow, pleasure',
    color: 'var(--chakra-sacral)',
    hex: '#dd7c5c',
    ageRange: { start: 7, end: 14 },
  },
  {
    id: 'solar',
    number: 3,
    name: 'Solar Plexus',
    sanskrit: 'Manipura',
    devanagari: 'मणिपूर',
    element: 'fire',
    planet: 'Sun',
    zodiac: ['Leo', 'Aries', 'Sagittarius'],
    location: 'Solar plexus',
    theme: 'Will, power, identity',
    color: 'var(--chakra-solar)',
    hex: '#d5a743',
    ageRange: { start: 14, end: 21 },
  },
  {
    id: 'heart',
    number: 4,
    name: 'Heart',
    sanskrit: 'Anahata',
    devanagari: 'अनाहत',
    element: 'air',
    planet: 'Venus',
    zodiac: ['Libra', 'Taurus'],
    location: 'Center of the chest',
    theme: 'Love, relating, balance',
    color: 'var(--chakra-heart)',
    hex: '#7ea158',
    ageRange: { start: 21, end: 28 },
  },
  {
    id: 'throat',
    number: 5,
    name: 'Throat',
    sanskrit: 'Vishuddha',
    devanagari: 'विशुद्ध',
    element: 'ether',
    planet: 'Mercury',
    zodiac: ['Gemini', 'Virgo'],
    location: 'Throat',
    theme: 'Voice, truth, expression',
    color: 'var(--chakra-throat)',
    hex: '#628db2',
    ageRange: { start: 28, end: 35 },
  },
  {
    id: 'thirdeye',
    number: 6,
    name: 'Third Eye',
    sanskrit: 'Ajna',
    devanagari: 'आज्ञा',
    element: 'light',
    planet: 'Jupiter',
    zodiac: ['Sagittarius', 'Pisces'],
    location: 'Between the brows',
    theme: 'Insight, vision, intuition',
    color: 'var(--chakra-thirdeye)',
    hex: '#6e6aa8',
    ageRange: { start: 35, end: 42 },
  },
  {
    id: 'crown',
    number: 7,
    name: 'Crown',
    sanskrit: 'Sahasrara',
    devanagari: 'सहस्रार',
    element: 'consciousness',
    planet: 'Neptune',
    zodiac: ['Pisces', 'Aquarius'],
    location: 'Top of the head',
    theme: 'Connection, meaning, presence',
    color: 'var(--chakra-crown)',
    hex: '#9f7bc0',
    ageRange: { start: 42, end: 49 },
  },
];

export function getChakra(id) {
  return CHAKRAS.find((c) => c.id === id) || null;
}

export function getChakraByNumber(n) {
  return CHAKRAS[n - 1] || null;
}
